### ISSUE TITLE
Обрыв выгрузки похожий на ошибку в коде

### ISSUE THREAD

**Issue by EvilBeaver** [TeamBIOS/cfg_tools#3]
Выгрузка прервалась. Фрагмент лога ниже:

```
2016-02-01 13:38:36,283    INFO: Store: Exporting version: 113
2016-02-01 13:38:36,283   DEBUG: Store: Saved 0 files
2016-02-01 13:38:36,284   DEBUG:   GIT: Executing "git add -A ."
2016-02-01 13:38:37,802   DEBUG:   GIT: Exit code: 0
2016-02-01 13:38:37,803   DEBUG:   GIT:
2016-02-01 13:38:37,803    INFO:   MNG: Commiting version: 113
2016-02-01 13:38:37,803   ERROR:  root: Выгрузка версий
Traceback (most recent call last):
  File "run.py", line 37, in <module>
    success = mng.export_new()
  File "c:\Distr\cfg_tools\mng.py", line 274, in export_new
    self.export_versions(start_version, commit=commit)
  File "c:\Distr\cfg_tools\mng.py", line 232, in export_versions
    self._commit(version_info)
  File "c:\Distr\cfg_tools\mng.py", line 116, in _commit
    date=version_info['date'])
  File "c:\Distr\cfg_tools\git_mng.py", line 58, in commit
    os.environ['GIT_AUTHOR_DATE'] = date.strftime('"%Y-%m-%d %H:%M:%S"')
AttributeError: 'str' object has no attribute 'strftime'
2016-02-01 13:38:37,807    INFO:  root: export delay: 728.8549990653992 sec.
```

Насколько я понимаю Питон, там внизу написано _"Свойство объекта не обнаружено 'strftime'"_

**Comment by TeamBIOS** [comment]
Ошибка связана с некорректным преобразованием даты. Сможете скинуть файл репозитория?

**Comment by EvilBeaver** [comment]
Нет, он жутко секретный и внутрикорпоративный (

**Comment by TeamBIOS** [comment]
Окей, это не беда. Доработаем немного лог. Позже сделаю коммит и отпишусь.

**Comment by TeamBIOS** [comment]
@EvilBeaver Обновил, попробуйте повторить выгрузку
